export const TEAM_MEMBEERS_REPOSITORY = 'TEAM_MEMBERS_REPOSITORY'
export const TEAM_MEMBEERS_IMAGE_REPOSITORY = 'TEAM_MEMBERS_IMAGE_REPOSITORY'
export const TEAM_MEMBERS_DIRECTORY_PATH = '/team_members'